package internal

const (
	ServerPrefix                    string = "server"
	FlagAddr                        string = "server.addr"
	FlagRecovery                    string = "server.recovery"
	FlagMaxConcurrentStreams        string = "server.max_concurrent_streams"
	FlagGrpcWeb                     string = "server.grpcweb.enable"
	FlagGrpcWebWithWs               string = "server.grpcweb.ws.enable"
	FlagHttpServer                  string = "server.http.enable"
	FlagHttpAddr                    string = "server.http.addr"
	FlagWithGrpcGatewayCompatible   string = "server.http.grpc_gateway_compatible"
	FlagWithPackageName             string = "server.http.with_package_name"
	FlagOrigName                    string = "server.http.json.orig_name"
	FlagEnumAsInts                  string = "server.http.json.enum_as_ints"
	FlagEmitDefaults                string = "server.http.json.emit_defaults"
	FlagHttpReadTimeout             string = "server.http.timeout.read"
	FlagHttpWriteTimeout            string = "server.http.timeout.write"
	FlagHttpIdleTimeout             string = "server.http.timeout.idle"
	FlagHttpKeepAlive               string = "server.http.keep_alive"
	FlagCert                        string = "server.tls.cert"
	FlagKey                         string = "server.tls.key"
	FlagCaCert                      string = "server.tls.cacert"
	FlagClientAuthType              string = "server.tls.client_auth_type"
	FlagClientAuthorities           string = "server.tls.client_authorities"
	FlagSelfSignCertSAN             string = "server.tls.self_cert.san"
	FlagInsecure                    string = "server.insecure"
	FlagAllowedOrigins              string = "server.cors.allowed_origins"
	FlagAllowedRequestHeaders       string = "server.cors.allowed_request_headers"
	FlagAllowedMethods              string = "server.cors.allowed_methods"
	FlagCorsLogger                  string = "server.cors.log.enable"
	FlagHttpGzip                    string = "server.http.gzip"
	FlagIgnoreInternalInterceptors  string = "server.no_internal_interceptors"
	FlagHealthServiceEnable         string = "server.healthy"
	FlagMaxHttpConcurrentConnection string = "server.http.max_concurrent_conns"
	FlagPortRange                   string = "server.addr.port_range"
	FlagCheckClientCertExpiration   string = "server.tls.check_client_cert_expiration"
	FlagLegacyHttpRegistry          string = "server.http.legacy_http_registry"
	FlagServerReflection            string = "server.grpc_reflection.enable"
	FlagServerReflectionToken       string = "server.grpc_reflection.token"

	AutoSelectAddr      = "auto"
	MultiplexServerAddr = "mux"
)
