// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package testpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Response struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "test.pb.Request")
	proto.RegisterType((*Response)(nil), "test.pb.Response")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0xb0, 0x93, 0x94, 0x64, 0xb9, 0xd8, 0x83,
	0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0x52, 0x12, 0x4b, 0x12, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x23, 0x2e, 0x8e, 0xa0, 0xd4, 0xe2, 0x82, 0xfc,
	0xbc, 0xe2, 0x54, 0x90, 0x7c, 0x72, 0x7e, 0x4a, 0x2a, 0x58, 0x5e, 0x30, 0x08, 0xcc, 0x86, 0xeb,
	0x61, 0x42, 0xe8, 0x31, 0xfa, 0xc9, 0xc8, 0xc5, 0x1e, 0x92, 0x5a, 0x5c, 0xe2, 0x58, 0x90, 0x29,
	0xa4, 0xc7, 0xc5, 0x1a, 0x9a, 0x97, 0x58, 0x54, 0x29, 0x24, 0xa0, 0x07, 0xb5, 0x51, 0x0f, 0x6a,
	0x9d, 0x94, 0x20, 0x92, 0x08, 0xc4, 0x06, 0x25, 0x06, 0x21, 0x3b, 0x2e, 0xe1, 0xe0, 0xd4, 0xa2,
	0xb2, 0xd4, 0xa2, 0xe0, 0xcc, 0x94, 0xd4, 0xe0, 0x92, 0xa2, 0xd4, 0xc4, 0xdc, 0xcc, 0xbc, 0x74,
	0x22, 0x75, 0x1b, 0x30, 0x82, 0xf4, 0x3b, 0xe7, 0x64, 0xa6, 0xe6, 0x95, 0x90, 0xa3, 0x5f, 0x03,
	0xa4, 0x5f, 0xd0, 0x29, 0x33, 0x25, 0x93, 0x3c, 0xdd, 0x06, 0x8c, 0x4e, 0x1c, 0x51, 0x6c, 0x20,
	0x99, 0x82, 0xa4, 0x24, 0x36, 0x70, 0x40, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x53, 0x64,
	0xa9, 0xaf, 0x76, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestApiClient is the client API for TestApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestApiClient interface {
	Unary(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	ServerSideStreaming(ctx context.Context, in *Request, opts ...grpc.CallOption) (TestApi_ServerSideStreamingClient, error)
	ClientSideStreaming(ctx context.Context, opts ...grpc.CallOption) (TestApi_ClientSideStreamingClient, error)
	BidiSideStreaming(ctx context.Context, opts ...grpc.CallOption) (TestApi_BidiSideStreamingClient, error)
}

type testApiClient struct {
	cc *grpc.ClientConn
}

func NewTestApiClient(cc *grpc.ClientConn) TestApiClient {
	return &testApiClient{cc}
}

func (c *testApiClient) Unary(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/test.pb.TestApi/Unary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testApiClient) ServerSideStreaming(ctx context.Context, in *Request, opts ...grpc.CallOption) (TestApi_ServerSideStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TestApi_serviceDesc.Streams[0], "/test.pb.TestApi/ServerSideStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &testApiServerSideStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TestApi_ServerSideStreamingClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type testApiServerSideStreamingClient struct {
	grpc.ClientStream
}

func (x *testApiServerSideStreamingClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *testApiClient) ClientSideStreaming(ctx context.Context, opts ...grpc.CallOption) (TestApi_ClientSideStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TestApi_serviceDesc.Streams[1], "/test.pb.TestApi/ClientSideStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &testApiClientSideStreamingClient{stream}
	return x, nil
}

type TestApi_ClientSideStreamingClient interface {
	Send(*Request) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type testApiClientSideStreamingClient struct {
	grpc.ClientStream
}

func (x *testApiClientSideStreamingClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *testApiClientSideStreamingClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *testApiClient) BidiSideStreaming(ctx context.Context, opts ...grpc.CallOption) (TestApi_BidiSideStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TestApi_serviceDesc.Streams[2], "/test.pb.TestApi/BidiSideStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &testApiBidiSideStreamingClient{stream}
	return x, nil
}

type TestApi_BidiSideStreamingClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type testApiBidiSideStreamingClient struct {
	grpc.ClientStream
}

func (x *testApiBidiSideStreamingClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *testApiBidiSideStreamingClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TestApiServer is the server API for TestApi service.
type TestApiServer interface {
	Unary(context.Context, *Request) (*Response, error)
	ServerSideStreaming(*Request, TestApi_ServerSideStreamingServer) error
	ClientSideStreaming(TestApi_ClientSideStreamingServer) error
	BidiSideStreaming(TestApi_BidiSideStreamingServer) error
}

func RegisterTestApiServer(s *grpc.Server, srv TestApiServer) {
	s.RegisterService(&_TestApi_serviceDesc, srv)
}

func _TestApi_Unary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestApiServer).Unary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.pb.TestApi/Unary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestApiServer).Unary(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestApi_ServerSideStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestApiServer).ServerSideStreaming(m, &testApiServerSideStreamingServer{stream})
}

type TestApi_ServerSideStreamingServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type testApiServerSideStreamingServer struct {
	grpc.ServerStream
}

func (x *testApiServerSideStreamingServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func _TestApi_ClientSideStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestApiServer).ClientSideStreaming(&testApiClientSideStreamingServer{stream})
}

type TestApi_ClientSideStreamingServer interface {
	SendAndClose(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type testApiClientSideStreamingServer struct {
	grpc.ServerStream
}

func (x *testApiClientSideStreamingServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *testApiClientSideStreamingServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TestApi_BidiSideStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestApiServer).BidiSideStreaming(&testApiBidiSideStreamingServer{stream})
}

type TestApi_BidiSideStreamingServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type testApiBidiSideStreamingServer struct {
	grpc.ServerStream
}

func (x *testApiBidiSideStreamingServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *testApiBidiSideStreamingServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TestApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "test.pb.TestApi",
	HandlerType: (*TestApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unary",
			Handler:    _TestApi_Unary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerSideStreaming",
			Handler:       _TestApi_ServerSideStreaming_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientSideStreaming",
			Handler:       _TestApi_ClientSideStreaming_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BidiSideStreaming",
			Handler:       _TestApi_BidiSideStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "test.proto",
}
